version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nos_dois_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: nos_dois
    volumes:
      - nos_dois_db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  nos_dois_db: